type Connection = {
  startId: number;
  midId?: number;
  endId: number;
  startAnchor?: 'top' | 'bottom' | 'left' | 'right';
  endAnchor?: 'top' | 'bottom' | 'left' | 'right';
  angled?: boolean;
};

export const FighterConnections: Connection[] = [
  { startId: 71, midId: 70, endId: 81, startAnchor: 'left', endAnchor: 'top'},
  { startId: 71, midId: 72, endId: 83, startAnchor: 'left', endAnchor: 'top'},
  { startId: 59, midId: 70, endId: 81, startAnchor: 'bottom', endAnchor: 'top'},
  { startId: 59, midId: 58, endId: 69, startAnchor: 'left', endAnchor: 'top'},
  { startId: 59, endId: 56, startAnchor: 'left', endAnchor: 'right'},
  { startId: 56, endId: 23, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 23, endId: 12, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 12, endId: 13, startAnchor: 'right', endAnchor: 'left'},
  { startId: 71, endId: 49, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 61, endId: 64, startAnchor: 'right', endAnchor: 'left'},
  { startId: 64, endId: 42, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 42, endId: 20, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 12, midId: 1, endId: 5, startAnchor: 'top', endAnchor: 'left' },
  { startId: 20, midId: 9, endId: 5, startAnchor: 'top', endAnchor: 'right' },
  { startId: 56, endId: 67, startAnchor: 'bottom', endAnchor: 'top'},
  { startId: 49, endId: 46, startAnchor: 'left', endAnchor: 'right'},
  { startId: 49, midId: 47, endId: 36, startAnchor: 'left', endAnchor: 'bottom'},
  { startId: 36, endId: 35, startAnchor: 'left', endAnchor: 'right'},
  { startId: 36, endId: 37, startAnchor: 'right', endAnchor: 'left'},
  { startId: 36, endId: 25, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 25, endId: 24, startAnchor: 'left', endAnchor: 'right'},
  { startId: 25, endId: 26, startAnchor: 'right', endAnchor: 'left'},
  { startId: 25, midId: 14, endId: 16, startAnchor: 'top', endAnchor: 'left'},
  { startId: 49, midId: 51, endId: 40, startAnchor: 'right', endAnchor: 'bottom'},
  { startId: 40, endId: 39, startAnchor: 'left', endAnchor: 'right'},
  { startId: 40, endId: 41, startAnchor: 'right', endAnchor: 'left'},
  { startId: 40, endId: 29, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 41, endId: 30, startAnchor: 'top', endAnchor: 'bottom'},
  { startId: 41, endId: 52, startAnchor: 'bottom', endAnchor: 'top'},
   { startId: 20, endId: 19, startAnchor: 'left', endAnchor: 'right'},
  { startId: 29, midId: 18, endId: 16, startAnchor: 'top', endAnchor: 'right'},
];

export type Coord = {
  id: number;
  x: number;
  y: number;
};

type Box = {
  id: number;
  imageUrl: string;
  hidden?: boolean;
};

export const boxes: Box[] = [
  { id: 1, imageUrl: '/Rupture.png', hidden: true},
  { id: 2, imageUrl: '/Rupture.png', hidden: true},
  { id: 3, imageUrl: '/Rupture.png', hidden: true},
  { id: 4, imageUrl: '/Rupture.png', hidden: true},
  { id: 5, imageUrl: '/fighterSkills/Art_of_War_Skill.png', hidden: false},
  { id: 6, imageUrl: '/Rupture.png', hidden: true},
  { id: 7, imageUrl: '/Rupture.png', hidden: true},
  { id: 8, imageUrl: '/Rupture.png', hidden: true},
  { id: 9, imageUrl: '/Rupture.png', hidden: true},
  { id: 10, imageUrl: '/Rupture.png', hidden: true},
  { id: 11, imageUrl: '/Rupture.png', hidden: true},
  { id: 12, imageUrl: '/fighterSkills/Form_of_Celerity_Skill.png', hidden: false},
  { id: 13, imageUrl: '/fighterSkills/Relentless_Form_of_the_Avalanche_Skill.png', hidden: false},
  { id: 14, imageUrl: '/Rupture.png', hidden: true},
  { id: 15, imageUrl: '/Rupture.png', hidden: true},
  { id: 16, imageUrl: '/fighterSkills/Cataclysm.png', hidden: false},
  { id: 17, imageUrl: '/Rupture.png', hidden: true},
  { id: 18, imageUrl: '/Rupture.png', hidden: true},
  { id: 19, imageUrl: '/fighterSkills/Meditative_Form_of_the_River_Skill.png', hidden: false},
  { id: 20, imageUrl: '/fighterSkills/Form_of_Fluidity.png', hidden: false},
  { id: 21, imageUrl: '/Rupture.png', hidden: true},
  { id: 22, imageUrl: '/Rupture.png', hidden: true},
  { id: 23, imageUrl: '/fighterSkills/Leap_Strike.png', hidden: false},
  { id: 24, imageUrl: '/fighterSkills/Reinvigorating_Exert_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 25, imageUrl: '/fighterSkills/Exert.png', hidden: false},
  { id: 26, imageUrl: '/fighterSkills/Reinvigorating_Exert_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 27, imageUrl: '/Rupture.png', hidden: true},
  { id: 28, imageUrl: '/Rupture.png', hidden: true},
  { id: 29, imageUrl: '/fighterSkills/Rupture.png', hidden: false},
  { id: 30, imageUrl: '/fighterSkills/Blood_Fusion.png', hidden: false},
  { id: 31, imageUrl: '/Rupture.png', hidden: true},
  { id: 32, imageUrl: '/Rupture.png', hidden: true},
  { id: 33, imageUrl: '/Rupture.png', hidden: true},
  { id: 34, imageUrl: '/Rupture.png', hidden: true},
  { id: 35, imageUrl: '/fighterSkills/Climactic_Whirlwind_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 36, imageUrl: '/fighterSkills/Whirlwind.png', hidden: false},
  { id: 37, imageUrl: '/fighterSkills/Climactic_Whirlwind_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 38, imageUrl: '/Rupture.png', hidden: true},
  { id: 39, imageUrl: '/fighterSkills/Slicing_Maim_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 40, imageUrl: '/fighterSkills/Maim.png', hidden: false},
  { id: 41, imageUrl: '/fighterSkills/Greater_Brutality_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 42, imageUrl: '/fighterSkills/Battle_Cry.png', hidden: false},
  { id: 43, imageUrl: '/Rupture.png', hidden: true},
  { id: 44, imageUrl: '/Rupture.png', hidden: true},
  { id: 45, imageUrl: '/Rupture.png', hidden: true},
  { id: 46, imageUrl: '/fighterSkills/Fighter_Momentum_Buff.png', hidden: false},
  { id: 47, imageUrl: '/Rupture.png', hidden: true},
  { id: 48, imageUrl: '/Rupture.png', hidden: true},
  { id: 49, imageUrl: '/fighterSkills/Brutal_Cleave.png', hidden: false},
  { id: 50, imageUrl: '/Rupture.png', hidden: true},
  { id: 51, imageUrl: '/Rupture.png', hidden: true},
  { id: 52, imageUrl: '/fighterSkills/Greater_Brutality_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 53, imageUrl: '/Rupture.png', hidden: true},
  { id: 54, imageUrl: '/Rupture.png', hidden: true},
  { id: 55, imageUrl: '/Rupture.png', hidden: true},
  { id: 56, imageUrl: '/fighterSkills/Lunging_Assault.png', hidden: false},
  { id: 57, imageUrl: '/Rupture.png', hidden: true},
  { id: 58, imageUrl: '/Rupture.png', hidden: true},
  { id: 59, imageUrl: '/fighterSkills/Blitz.png', hidden: false},
  { id: 60, imageUrl: '/Rupture.png', hidden: true},
  { id: 61, imageUrl: '/fighterSkills/Crippling_Blow.png', hidden: false},
  { id: 62, imageUrl: '/Rupture.png', hidden: true},
  { id: 63, imageUrl: '/Rupture.png', hidden: true},
  { id: 64, imageUrl: '/fighterSkills/Knock_Out.png', hidden: false},
  { id: 65, imageUrl: '/Rupture.png', hidden: true},
  { id: 66, imageUrl: '/Rupture.png', hidden: true},
  { id: 67, imageUrl: '/fighterSkills/Recharging_Lunging_Assault_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 68, imageUrl: '/Rupture.png', hidden: true},
  { id: 69, imageUrl: '/fighterSkills/Raging_Blitz_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 70, imageUrl: '/Rupture.png', hidden: true},
  { id: 71, imageUrl: '/fighterSkills/Lethal_Blow.png', hidden: false},
  { id: 72, imageUrl: '/Rupture.png', hidden: true},
  { id: 73, imageUrl: '/Rupture.png', hidden: true},
  { id: 74, imageUrl: '/Rupture.png', hidden: true},
  { id: 75, imageUrl: '/Rupture.png', hidden: true},
  { id: 76, imageUrl: '/Rupture.png', hidden: true},
  { id: 77, imageUrl: '/fighterSkills/Overpower.png', hidden: false},
  { id: 78, imageUrl: '/Rupture.png', hidden: true},
  { id: 79, imageUrl: '/Rupture.png', hidden: true},
  { id: 80, imageUrl: '/Rupture.png', hidden: true},
  { id: 81, imageUrl: '/fighterSkills/Raging_Blitz_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 82, imageUrl: '/Rupture.png', hidden: true},
  { id: 83, imageUrl: '/fighterSkills/Consuming_Lethal_Blow_Skill_Tree_IconAlpha.png', hidden: false},
  { id: 84, imageUrl: '/Rupture.png', hidden: true},
  { id: 85, imageUrl: '/Rupture.png', hidden: true},
  { id: 86, imageUrl: '/Rupture.png', hidden: true},
  { id: 87, imageUrl: '/Rupture.png', hidden: true},
  { id: 88, imageUrl: '/fighterSkills/Form_Of_Ferocity.png', hidden: false},
  { id: 89, imageUrl: '/Rupture.png', hidden: true},
  { id: 90, imageUrl: '/Rupture.png', hidden: true},
  { id: 91, imageUrl: '/Rupture.png', hidden: true},
  { id: 92, imageUrl: '/Rupture.png', hidden: true},
  { id: 93, imageUrl: '/Rupture.png', hidden: true},
  { id: 94, imageUrl: '/Rupture.png', hidden: true},
  { id: 95, imageUrl: '/Rupture.png', hidden: true},
  { id: 96, imageUrl: '/Rupture.png', hidden: true},
  { id: 97, imageUrl: '/Rupture.png', hidden: true},
  { id: 98, imageUrl: '/Rupture.png', hidden: true},
  { id: 99, imageUrl: '/fighterSkills/Combat_Momentum_Skill_Tree_IconAlpha.png', hidden: false},
];