import NextAuthSessionProvider from '@/providers/sessionProvider';
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Emporium Of Verra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
