import { Skill } from '@/types';

export const ShortBowSkills : Skill[] = [
  {
    id: 1,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 2,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 3,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 4,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency IV',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 5,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency V',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 6,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency VI',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency VII',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 8,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency VII',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 9,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency IX',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 10,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FKeen_Edge.png?alt=media&token=5c1d5b11-59a9-44d7-8e07-1764478b2656',
    name: 'Weapon Proficiency X',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 11,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 12,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 13,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 14,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge IV',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 15,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge V',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 16,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge VI',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 17,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge VII',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 18,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge VIII',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 19,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge IX',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 20,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FWeapon%20Proficiency.png?alt=media&token=060ee103-8f2c-4c54-8d01-80edf6f512e5',
    name: 'Keen Edge X',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 21,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FShortbow_Hit_5.png?alt=media&token=0ea497a5-62d0-40ba-a2fa-6c8966574fbd',
    name: 'Short Bow Hit 5',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 22,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FShortbow_Hit_5%2B.png?alt=media&token=193b47f9-60da-4a15-9d5e-c28caa4217a7',
    name: 'Short Bow Hit 5+',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 23,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FShortbow_Hit_6.png?alt=media&token=2dea69f1-31c3-40d3-9d98-e0ddda0d5209',
    name: 'Short Bow Hit 6',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 24,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/ShortBowSkills%2FShortbow_Hit_6%2B.png?alt=media&token=4d5e6aff-2e77-4e16-95a3-c2997c5d4bc7',
    name: 'Short Bow Hit 6+',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  }
]