import { Skill } from '@/types';

export const WandSkills : Skill[] = [
  {
    id: 0,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWeaponSkillSelectIcon.png?alt=media&token=72d791be-efa5-4004-aefa-c82a92cd1083',
    name: 'Changed Passive Pos 5',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
    changedSkill: true,
  },
  {
    id: 1,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Projectile_Damage_1.png?alt=media&token=77cc855f-0308-4825-97c6-ff064a036c84',
    name: 'Wand Damage Focus I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 2,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Projectile_Damage_2.png?alt=media&token=629de6fb-a1bb-4566-9f83-00459b255a79',
    name: 'Wand Damage Focus II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 3,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Projectile_Damage_3.png?alt=media&token=135fc913-2991-4e49-9eb3-77bd3403cceb',
    name: 'Wand Damage Focus III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 4,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FExtended_Duration_1.png?alt=media&token=39a29aef-b4b3-4f7b-94df-4a3357883f08',
    name: 'Extended Duration I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 5,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FExtended_Duration_2.png?alt=media&token=2abb35de-b9d5-414c-9e8e-bdb340415d8d',
    name: 'Extended Duration II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 6,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FExtended_Duration_3.png?alt=media&token=d16c96d3-d299-4aea-a22d-b19486da74e9',
    name: 'Extended Duration III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FExtra_Stacks_1.png?alt=media&token=39b7f9f0-ef41-4847-821a-9040e5c59caf',
    name: 'Extra Stacks I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 8,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FExtra_Stacks_2.png?alt=media&token=4f8dccb5-7d3f-4497-aea4-674c7b5526bc',
    name: 'Extra Stacks II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 9,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FExtra_Stacks_3.png?alt=media&token=eaab6c71-464f-4fa4-9bb4-35f65c9d222b',
    name: 'Extra Stacks III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  }
  ,
  {
    id: 10,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FHit_Proc_Chance_I.png?alt=media&token=59c40ef6-4b43-4226-ac55-5fd3fc4deb15',
    name: 'Hit 6+ Chance Proc I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 11,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FHit_Proc_Chance_II.png?alt=media&token=6540a079-dbc5-4f81-9840-ca04793fea0d',
    name: 'Hit 6+ Chance Proc II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 12,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FHit_Proc_Chance_III.png?alt=media&token=57cde89c-0ea2-4f61-8e8a-0b3c2e58b590',
    name: 'Hit 6+ Chance Proc III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 13,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B.png?alt=media&token=a2975ffb-108f-416d-92b7-c3e13d41550d',
    name: 'Wand Hit 6+',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 14,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B_Extra_Damage_I.png?alt=media&token=afe44e24-45d2-4872-a3b9-17e27b106cef',
    name: 'Wand Hit 6+ Extra Damage I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 15,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B_Extra_Damage_II.png?alt=media&token=74aa9115-aa24-4709-b4a9-d68a01beb8dc',
    name: 'Wand Hit 6+ Extra Damage II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 16,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B_Extra_Damage_III.png?alt=media&token=333858de-ad74-4576-b1d2-6dd3c30e54bf',
    name: 'Wand Hit 6+ Extra Damage III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 17,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6_Extra_Damage_I.png?alt=media&token=027f4a9d-ef22-4531-a167-a240c534cf28',
    name: 'Wand Hit 6 Extra Damage I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 18,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6_Extra_Damage_II.png?alt=media&token=5d16bd7b-aa24-4ea6-9fb1-611f2bf2b627',
    name: 'Wand Hit 6 Extra Damage II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 19,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6_Extra_Damage_III.png?alt=media&token=062d8f5a-70ad-4716-9e29-15166f1538d3',
    name: 'Wand Hit 6 Extra Damage III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 20,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWeaponSkillSelectIcon.png?alt=media&token=72d791be-efa5-4004-aefa-c82a92cd1083',
    name: 'Changed Passive Pos 17',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 21,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FBeam_Amplifier.png?alt=media&token=6d63b8e4-5d63-4451-8534-e626832d016c',
    name: 'Beam Amplification',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 22,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6.png?alt=media&token=e396a9a7-7a43-420c-9257-fc4e0c755fe6',
    name: 'Wand Hit 6',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 23,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FEssence_Harvest.png?alt=media&token=119fe3d3-750a-402e-ab01-3f1eb10eb731',
    name: 'Essence Harvest',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 24,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6_Extra_Damage_I.png?alt=media&token=027f4a9d-ef22-4531-a167-a240c534cf28',
    name: 'Wand Hit 5 Extra Damage I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 25,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6_Extra_Damage_II.png?alt=media&token=5d16bd7b-aa24-4ea6-9fb1-611f2bf2b627',
    name: 'Wand Hit 5 Extra Damage II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 26,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6_Extra_Damage_III.png?alt=media&token=062d8f5a-70ad-4716-9e29-15166f1538d3',
    name: 'Wand Hit 5 Extra Damage III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 27,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FElemental_Lure_1.png?alt=media&token=d12d4431-469f-43da-8e5e-06241f11854c',
    name: 'Elemental Lure I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 28,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FElemental_Lure_2.png?alt=media&token=8d35ae53-c33e-4c70-9b47-5d7d7f2e109c',
    name: 'Elemental Lure II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 29,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FElemental_Lure_3.png?alt=media&token=f272122f-4838-4388-828c-dbbc43b60ad9',
    name: 'Elemental Lure III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 30,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FElemental_Attunement_1.png?alt=media&token=09cc96fe-8230-47b2-a75e-3b7a4a14354f',
    name: 'Elemental Attunement I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 31,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FElemental_Attunement_2.png?alt=media&token=0e847b17-bf89-4395-a533-2ef5ff0ab6c4',
    name: 'Elemental Attunement II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 32,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FElemental_Attunement_3.png?alt=media&token=85905edd-f4cb-4d04-ae69-a443ffa227dd',
    name: 'Elemental Attunement III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 33,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FHit_Proc_Chance_I.png?alt=media&token=59c40ef6-4b43-4226-ac55-5fd3fc4deb15',
    name: 'Wand Hit 5 Proc Chance I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 34,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FHit_Proc_Chance_II.png?alt=media&token=6540a079-dbc5-4f81-9840-ca04793fea0d',
    name: 'Wand Hit 5 Proc Chance II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 35,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FHit_Proc_Chance_III.png?alt=media&token=57cde89c-0ea2-4f61-8e8a-0b3c2e58b590',
    name: 'Wand Hit 5 Proc Chance III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 36,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B_Extra_Damage_I.png?alt=media&token=afe44e24-45d2-4872-a3b9-17e27b106cef',
    name: 'Wand Hit 6 Extra Damage I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 37,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B_Extra_Damage_II.png?alt=media&token=74aa9115-aa24-4709-b4a9-d68a01beb8dc',
    name: 'Wand Hit 6 Extra Damage II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 38,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B_Extra_Damage_III.png?alt=media&token=333858de-ad74-4576-b1d2-6dd3c30e54bf',
    name: 'Wand Hit 6 Extra Damage III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 39,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Damage_Focus_1.png?alt=media&token=43398c00-eb9d-4662-89d6-58638d59f3c3',
    name: 'Wand Damage Focus I',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 40,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Damage_Focus_2.png?alt=media&token=d9cd3051-69cd-47f5-a8f9-8d31b65cddea',
    name: 'Wand Damage Focus II',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 41,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Damage_Focus_3.png?alt=media&token=2eb4e0ff-b32b-43b4-b859-9d4e520297f8',
    name: 'Wand Damage Focus III',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 42,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Weapon_Training_Power.png?alt=media&token=8e73a2c0-5439-41c8-82a9-55ee2bc524b9',
    name: 'Weapon Training Power',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 43,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWand_Hit_6%2B.png?alt=media&token=a2975ffb-108f-416d-92b7-c3e13d41550d',
    name: 'Wand Hit 5+',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 44,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWeaponSkillSelectIcon.png?alt=media&token=72d791be-efa5-4004-aefa-c82a92cd1083',
    name: 'Changed Passive Pos 101',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 45,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWeaponSkillSelectIcon.png?alt=media&token=72d791be-efa5-4004-aefa-c82a92cd1083',
    name: 'Changed Passive',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 46,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWeaponSkillSelectIcon.png?alt=media&token=72d791be-efa5-4004-aefa-c82a92cd1083',
    name: 'Changed Passive',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 47,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWeaponSkillSelectIcon.png?alt=media&token=72d791be-efa5-4004-aefa-c82a92cd1083',
    name: 'Changed Passive Pos 7',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 48,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/WandSkills%2FWeaponSkillSelectIcon.png?alt=media&token=72d791be-efa5-4004-aefa-c82a92cd1083',
    name: 'Changed Passive Pos 13',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  }
]