import { Skill } from '@/types';

export const fighterSkills : Skill[] = [
  {
    id: 1,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FAct_of_War.png?alt=media&token=1308f962-284c-4be8-86c9-2603691900ce',
    name: 'Art Of War',
    description: 'Switching forms no longer triggers cooldowns or costs Combat Momentum.',
    isActive: false,
    level: '1',
    cooldown: '30 Sec',
    range: '30m',
  },
  {
    id: 2,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FForm_of_Celerity.png?alt=media&token=70a436b9-f1b9-4aca-94e5-07847545bebb',
    name: 'Form Of Celerity',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 3,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FRelentless_Form_of_the_Avalanche.png?alt=media&token=ac9e70ca-7877-4d43-988d-cd82ff404c73',
    name: 'Relentless Form of the Avalanche',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 4,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FCataclysm.png?alt=media&token=75710cb6-4f37-44ce-8cb6-39d295ab2541',
    name: 'Cataclysm',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 5,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FForm_of_Fluidity.png?alt=media&token=f1282f19-f5ac-4212-a0f5-5d02a45ff83d',
    name: 'Meditative Form of the River',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 6,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FForm_of_Fluidity.png?alt=media&token=f1282f19-f5ac-4212-a0f5-5d02a45ff83d',
    name: 'Form Of Fluidity',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FLeap_Strike.png?alt=media&token=d2e5b1dd-0127-4310-88d9-21aa0a8d16ac',
    name: 'Leap Strike',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 8,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FExert.png?alt=media&token=03a2cf00-08a5-4570-afcf-b5f41e37766e',
    name: 'Unstoppable Exert',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 9,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FExert.png?alt=media&token=03a2cf00-08a5-4570-afcf-b5f41e37766e',
    name: 'Exert',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 10,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FExert.png?alt=media&token=03a2cf00-08a5-4570-afcf-b5f41e37766e',
    name: 'Reinvigorating Exert',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 11,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FRupture.png?alt=media&token=6a724079-9973-4c3f-8aea-dfac88dc31d9',
    name: 'Rupture',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 12,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FBlood_Fusion.png?alt=media&token=39459d1d-a2a2-4349-b96a-4e5585aa3a56',
    name: 'Blood Fusion',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 13,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FWhirlwind.png?alt=media&token=12a4fc19-7424-4f14-a2c6-02846e4885e2',
    name: 'Whirlwind Overdrive',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 14,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FWhirlwind.png?alt=media&token=12a4fc19-7424-4f14-a2c6-02846e4885e2',
    name: 'Whirlwind',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 15,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FWhirlwind.png?alt=media&token=12a4fc19-7424-4f14-a2c6-02846e4885e2',
    name: 'Climactic Whirlwind',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 16,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FMaim.png?alt=media&token=8c1fbc22-58aa-44e7-a60d-ef7610d3ea12',
    name: 'Slicing Maim',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 17,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FMaim.png?alt=media&token=8c1fbc22-58aa-44e7-a60d-ef7610d3ea12',
    name: 'Slicing Maim',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 18,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FGreater_Brutality.png?alt=media&token=167f46c1-02b8-4fe8-a389-d34939de716c',
    name: 'Brutality',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 19,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FBattle_Cry.png?alt=media&token=41bad92f-cbbe-4d2b-93e8-0801c2ef0f38',
    name: 'Battle Cry',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 20,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FFighter_Momentum_Buff.png?alt=media&token=b1e56337-83f8-4acb-8124-3acb60f0a8ff',
    name: 'Fighter WIP',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 21,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FBrutal_Cleave.png?alt=media&token=d6aa20fc-a193-4557-a3f5-20f8a6ca0a3b',
    name: 'Brutal Cleave',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 22,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FGreater_Brutality.png?alt=media&token=167f46c1-02b8-4fe8-a389-d34939de716c',
    name: 'Greater Brutality',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 23,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FLunging_Assault.png?alt=media&token=8ac0ac5e-9dad-481c-b5f1-7203f59cebe9',
    name: 'Lunging Assault',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 24,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FBlitz.png?alt=media&token=84ac3373-751b-4b2e-bb91-bb5df78befc8',
    name: 'Blitz',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 25,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FCrippling_Blow.png?alt=media&token=ae581228-0593-4a01-9d40-6721298e3807',
    name: 'Crippling Blow',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 26,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FKnock_Out.png?alt=media&token=831c84a2-347d-4f91-bd96-9304f588f1d0',
    name: 'Knock Out',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 27,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FLunging_Assault.png?alt=media&token=8ac0ac5e-9dad-481c-b5f1-7203f59cebe9',
    name: 'Recharging Lunging Assault',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 28,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FBlitz.png?alt=media&token=84ac3373-751b-4b2e-bb91-bb5df78befc8',
    name: 'Raging Blitz',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 29,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FLethal_Blow.png?alt=media&token=c216f24f-621d-49d9-afd1-60876b0af67a',
    name: 'Lethal Blow',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 30,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FOverpower.png?alt=media&token=b8b52d4a-c8c2-4174-8a00-af36e902f4cd',
    name: 'Overpower',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 31,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FBlitz.png?alt=media&token=84ac3373-751b-4b2e-bb91-bb5df78befc8',
    name: 'Reinvigorating Lethal Blow',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 32,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FLethal_Blow.png?alt=media&token=c216f24f-621d-49d9-afd1-60876b0af67a',
    name: 'Consuming Lethal Blow',
    description: '',
    isActive: false,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 33,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FForm_Of_Ferocity.png?alt=media&token=6be7ca38-d992-4b7d-82b7-f46f49bc836c',
    name: 'Form Of Ferocity',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
  {
    id: 34,
    image: 'https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/FighterSkills%2FFighter_Momentum_Buff.png?alt=media&token=b1e56337-83f8-4acb-8124-3acb60f0a8ff',
    name: 'Combat Momentum',
    description: '',
    isActive: true,
    level: '',
    cooldown: '',
    range: '',
  },
]