// constants/skillTreeData.ts
import { SkillTreeData } from '@/types';
import { fighterSkills } from '@/constants/ClassData/SkillsFighter';

export const skillTreeClass: { [key: string]: SkillTreeData } = {
  Fighter: {
    enabled: true,
    backgroundImage: '/background.jpg',
    skills: [
      { id: 5, skill: fighterSkills[0]},
      { id: 12, skill: fighterSkills[1]},
      { id: 13, skill: fighterSkills[2]},
      { id: 16, skill: fighterSkills[3]},
      { id: 19, skill: fighterSkills[4]},
      { id: 20, skill: fighterSkills[5]},
      { id: 23, skill: fighterSkills[6]},
      { id: 24, skill: fighterSkills[7]},
      { id: 25, skill: fighterSkills[8]},
      { id: 26, skill: fighterSkills[9]},
      { id: 29, skill: fighterSkills[10]},
      { id: 30, skill: fighterSkills[11]},
      { id: 35, skill: fighterSkills[12]},
      { id: 36, skill: fighterSkills[13]},
      { id: 37, skill: fighterSkills[14]},
      { id: 39, skill: fighterSkills[15]},
      { id: 40, skill: fighterSkills[16]},
      { id: 41, skill: fighterSkills[17]},
      { id: 42, skill: fighterSkills[18]},
      { id: 46, skill: fighterSkills[19]},
      { id: 49, skill: fighterSkills[20]},
      { id: 52, skill: fighterSkills[21]},
      { id: 56, skill: fighterSkills[22]},
      { id: 59, skill: fighterSkills[23]},
      { id: 61, skill: fighterSkills[24]},
      { id: 64, skill: fighterSkills[25]},
      { id: 67, skill: fighterSkills[26]},
      { id: 69, skill: fighterSkills[27]},
      { id: 71, skill: fighterSkills[28]},
      { id: 77, skill: fighterSkills[29]},
      { id: 81, skill: fighterSkills[30]},
      { id: 83, skill: fighterSkills[31]},
      { id: 88, skill: fighterSkills[32]},
      { id: 99, skill: fighterSkills[33]}
    ],
    connections: [
      { startId: 71, midId: 70, endId: 81, startAnchor: 'left', endAnchor: 'top'},
      { startId: 71, midId: 72, endId: 83, startAnchor: 'left', endAnchor: 'top'},
      { startId: 59, midId: 70, endId: 81, startAnchor: 'bottom', endAnchor: 'top'},
      { startId: 59, midId: 58, endId: 69, startAnchor: 'left', endAnchor: 'top'},
      { startId: 59, endId: 56, startAnchor: 'left', endAnchor: 'right'},
      { startId: 56, endId: 23, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 23, endId: 12, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 12, endId: 13, startAnchor: 'right', endAnchor: 'left'},
      { startId: 71, endId: 49, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 61, endId: 64, startAnchor: 'right', endAnchor: 'left'},
      { startId: 64, endId: 42, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 42, endId: 20, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 12, midId: 1, endId: 5, startAnchor: 'top', endAnchor: 'left' },
      { startId: 20, midId: 9, endId: 5, startAnchor: 'top', endAnchor: 'right' },
      { startId: 56, endId: 67, startAnchor: 'bottom', endAnchor: 'top'},
      { startId: 49, endId: 46, startAnchor: 'left', endAnchor: 'right'},
      { startId: 49, midId: 47, endId: 36, startAnchor: 'left', endAnchor: 'bottom'},
      { startId: 36, endId: 35, startAnchor: 'left', endAnchor: 'right'},
      { startId: 36, endId: 37, startAnchor: 'right', endAnchor: 'left'},
      { startId: 36, endId: 25, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 25, endId: 24, startAnchor: 'left', endAnchor: 'right'},
      { startId: 25, endId: 26, startAnchor: 'right', endAnchor: 'left'},
      { startId: 25, midId: 14, endId: 16, startAnchor: 'top', endAnchor: 'left'},
      { startId: 49, midId: 51, endId: 40, startAnchor: 'right', endAnchor: 'bottom'},
      { startId: 40, endId: 39, startAnchor: 'left', endAnchor: 'right'},
      { startId: 40, endId: 41, startAnchor: 'right', endAnchor: 'left'},
      { startId: 40, endId: 29, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 41, endId: 30, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 41, endId: 52, startAnchor: 'bottom', endAnchor: 'top'},
      { startId: 20, endId: 19, startAnchor: 'left', endAnchor: 'right'},
      { startId: 29, midId: 18, endId: 16, startAnchor: 'top', endAnchor: 'right'},
    ],
  },
  Ranger: {
    enabled: true,
    backgroundImage: 'https://c4.wallpaperflare.com/wallpaper/902/546/372/street-fighter-street-fighter-v-video-games-ryu-street-fighter-wallpaper-preview.jpg',
    skills: [
      { id: 5, skill: fighterSkills[0]},
      { id: 12, skill: fighterSkills[0]},
      { id: 13, skill: fighterSkills[0]},
      { id: 16, skill: fighterSkills[0]},
      { id: 19, skill: fighterSkills[0]},
      { id: 20, skill: fighterSkills[0]},
      { id: 23, skill: fighterSkills[0]},
      { id: 24, skill: fighterSkills[0]},
      { id: 25, skill: fighterSkills[0]},
      { id: 26, skill: fighterSkills[0]},
      { id: 29, skill: fighterSkills[0]},
      { id: 30, skill: fighterSkills[0]},
      { id: 35, skill: fighterSkills[0]},
      { id: 36, skill: fighterSkills[0]},
      { id: 37, skill: fighterSkills[0]},
      { id: 39, skill: fighterSkills[0]},
      { id: 40, skill: fighterSkills[0]},
      { id: 41, skill: fighterSkills[0]},
      { id: 42, skill: fighterSkills[0]},
      { id: 46, skill: fighterSkills[0]},
      { id: 49, skill: fighterSkills[0]},
      { id: 52, skill: fighterSkills[0]},
      { id: 56, skill: fighterSkills[0]},
      { id: 59, skill: fighterSkills[0]},
      { id: 61, skill: fighterSkills[0]},
      { id: 64, skill: fighterSkills[0]},
      { id: 67, skill: fighterSkills[0]},
      { id: 69, skill: fighterSkills[0]},
      { id: 71, skill: fighterSkills[0]},
      { id: 77, skill: fighterSkills[0]},
      { id: 81, skill: fighterSkills[0]},
      { id: 83, skill: fighterSkills[0]},
      { id: 88, skill: fighterSkills[0]},
      { id: 99, skill: fighterSkills[0]}
    ],
    connections: [
      { startId: 71, midId: 70, endId: 81, startAnchor: 'left', endAnchor: 'top'},
      { startId: 71, midId: 72, endId: 83, startAnchor: 'left', endAnchor: 'top'},
      { startId: 59, midId: 70, endId: 81, startAnchor: 'bottom', endAnchor: 'top'},
      { startId: 59, midId: 58, endId: 69, startAnchor: 'left', endAnchor: 'top'},
      { startId: 59, endId: 56, startAnchor: 'left', endAnchor: 'right'},
      { startId: 56, endId: 23, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 23, endId: 12, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 12, endId: 13, startAnchor: 'right', endAnchor: 'left'},
      { startId: 71, endId: 49, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 61, endId: 64, startAnchor: 'right', endAnchor: 'left'},
      { startId: 64, endId: 42, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 42, endId: 20, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 13, midId: 2, endId: 5, startAnchor: 'top', endAnchor: 'left' },
      { startId: 16, endId: 5, startAnchor: 'top', endAnchor: 'bottom' },
      { startId: 56, endId: 67, startAnchor: 'bottom', endAnchor: 'top'},
      { startId: 49, endId: 46, startAnchor: 'left', endAnchor: 'right'},
      { startId: 49, midId: 47, endId: 36, startAnchor: 'left', endAnchor: 'bottom'},
      { startId: 36, endId: 35, startAnchor: 'left', endAnchor: 'right'},
      { startId: 36, endId: 37, startAnchor: 'right', endAnchor: 'left'},
      { startId: 36, endId: 25, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 25, endId: 24, startAnchor: 'left', endAnchor: 'right'},
      { startId: 25, endId: 26, startAnchor: 'right', endAnchor: 'left'},
      { startId: 25, midId: 14, endId: 16, startAnchor: 'top', endAnchor: 'left'},
      { startId: 49, midId: 51, endId: 40, startAnchor: 'right', endAnchor: 'bottom'},
      { startId: 40, endId: 39, startAnchor: 'left', endAnchor: 'right'},
      { startId: 40, endId: 41, startAnchor: 'right', endAnchor: 'left'},
      { startId: 40, endId: 29, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 41, endId: 30, startAnchor: 'top', endAnchor: 'bottom'},
      { startId: 41, endId: 52, startAnchor: 'bottom', endAnchor: 'top'},
      { startId: 20, endId: 19, startAnchor: 'left', endAnchor: 'right'},
      { startId: 29, midId: 18, endId: 16, startAnchor: 'top', endAnchor: 'right'},
    ],
  },
};
